### ISSUE TITLE
Add releases

### ISSUE THREAD

**Issue by ynnckcmprnl** [PhotoPay/photopay-ios#3]
The Quick Start section mentions downloading the latest release to obtain the PhotoPay.xcframework, yet there are no releases, nor tags.

**Comment by somyaguptagit** [comment]
Hello Yannick,

Unfortunately PhotoPay is not distributed via Github but via Developer Hub. You can contact our sales team at sales@microblink.com in order to get registered on Developer Hub.

Let us know if you have any other questions.
