### ISSUE TITLE
Swift Compiler Warning - Umbrella header for module 'PhotoPay' does not include header 'MBFullDocumentImageDpi.h'

### ISSUE THREAD

**Issue by woutergoossens** [PhotoPay/photopay-ios#6]
We added the latest iOS SDK (8.1), but we receive the following warning:

`/.../PhotoPay.framework/Headers/PhotoPay.h:40:1: Umbrella header for module 'PhotoPay' does not include header 'MBFullDocumentImageDpi.h'`

As we treat warnings as errors, we cannot build our project unless this is fixed.. 
Would that be possible? Thanks

**Comment by mparadina** [comment]
Hi @woutergoossens 

Just to double-check, are you receving the warning when building the sample application as well?
Are you getting any additional warnings along with the mentioned one?

**Comment by woutergoossens** [comment]
Hi,

Yes indeed. Or when I add the SDK to a clean project, same issue.

Wouter

**Comment by mparadina** [comment]
Hi @woutergoossens 

I've managed to reproduce the issue.
For now, can you please do the following:

1. Go to PhotoPay.xcframework > ios-arm64 (or simulator and Mac Catalyst) > PhotoPay.framework > Headers > PhotoPay.h 
2. Open PhotoPay.h and the end of the file (line 40), add: `#import "MBFullDocumentImageDpi.h"`

After this modification, try to 'Clean build folder' and see if the warning is still present.

I will also notify the team regarding the mentioned warning and let you know their feedback.

**Comment by mparadina** [comment]
Hi @woutergoossens 

Did you manage to test out the mentioned solution?

**Comment by woutergoossens** [comment]
@mparadina Yes it worked, thanks! ;)

**Comment by mparadina** [comment]
@woutergoossens that is great news!

In that case, I am closing the issue.
If anything comes up related to the topic, let me know by reopening the issue or creating a new one.
